#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PIC_2018.Resource", IsApplication=true)]

namespace PIC_2018
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int fab_margin = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int standard_100 = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int standard_12 = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int standard_145 = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int standard_23 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int standard_55 = 2130968579;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_focus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_press = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_unfocused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int img01 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int img02 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int img03 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int img04 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int button1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
