#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PIC_2018.Resource", IsApplication=true)]

namespace PIC_2018
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b02 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b03 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int b04 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int b05 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logoFULL = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int button01 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int button02 = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int mainB01 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int mainB02 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int mainB03 = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int mainB04 = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int promBBack = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int textView1 = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Gestacao = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Prevencao = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Promocao = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Protecao = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int StartLayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
