#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PIC_2018.Resource", IsApplication=true)]

namespace PIC_2018
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int b01 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b04 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int b100 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int b102 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int b103 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int b104 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int b105 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int b200 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int b201 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int b202 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int b203 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int b204 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int b205 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int b206 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int b207 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int b208 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int b209 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int b210 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int b211 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int b300 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int b301 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int b302 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int b303 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int b304 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int b305 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int b306 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int b307 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int b308 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int b309 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int b310 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int b311 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int logo = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int logoFULL = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int objetivosMilenio = 2130837537;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050019
			public const int BUT_DesGra = 2131034137;
			
			// aapt resource value: 0x7f05002b
			public const int BUT_Doencas = 2131034155;
			
			// aapt resource value: 0x7f050031
			public const int BUT_EA = 2131034161;
			
			// aapt resource value: 0x7f05001a
			public const int BUT_EvoBeb = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int BUT_ExaGest = 2131034136;
			
			// aapt resource value: 0x7f050030
			public const int BUT_MC = 2131034160;
			
			// aapt resource value: 0x7f05001c
			public const int BUT_MudCorp = 2131034140;
			
			// aapt resource value: 0x7f050020
			public const int BUT_Nomes = 2131034144;
			
			// aapt resource value: 0x7f05002d
			public const int BUT_OM = 2131034157;
			
			// aapt resource value: 0x7f05002f
			public const int BUT_PG = 2131034159;
			
			// aapt resource value: 0x7f050022
			public const int BUT_PrimCuid = 2131034146;
			
			// aapt resource value: 0x7f050026
			public const int BUT_RisPuer = 2131034150;
			
			// aapt resource value: 0x7f05001d
			public const int BUT_Roupas = 2131034141;
			
			// aapt resource value: 0x7f05002e
			public const int BUT_SUS = 2131034158;
			
			// aapt resource value: 0x7f050021
			public const int BUT_SinPart = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int BUT_Sono = 2131034142;
			
			// aapt resource value: 0x7f050024
			public const int BUT_TiposPart = 2131034148;
			
			// aapt resource value: 0x7f05002a
			public const int BUT_gesta = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int BUT_preve = 2131034153;
			
			// aapt resource value: 0x7f050028
			public const int BUT_promo = 2131034152;
			
			// aapt resource value: 0x7f050015
			public const int BUT_trim1 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int BUT_trim2 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int BUT_trim3 = 2131034135;
			
			// aapt resource value: 0x7f050027
			public const int button02 = 2131034151;
			
			// aapt resource value: 0x7f050010
			public const int gono = 2131034128;
			
			// aapt resource value: 0x7f05000a
			public const int hepa = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int herp = 2131034130;
			
			// aapt resource value: 0x7f05000c
			public const int hiv = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int hpv = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int imageView1 = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int infoData = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout10 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout11 = 2131034131;
			
			// aapt resource value: 0x7f050023
			public const int linearLayout12 = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int linearLayout13 = 2131034149;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout3 = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout4 = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayout5 = 2131034123;
			
			// aapt resource value: 0x7f05001b
			public const int linearLayout6 = 2131034139;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout7 = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int linearLayout8 = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayout9 = 2131034143;
			
			// aapt resource value: 0x7f050006
			public const int mainB04 = 2131034118;
			
			// aapt resource value: 0x7f05002c
			public const int promBBack = 2131034156;
			
			// aapt resource value: 0x7f050001
			public const int scrollView1 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int sifi = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			// aapt resource value: 0x7f050014
			public const int trico = 2131034132;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Daids = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dclam = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dgono = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Dhepa = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DhepaC = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Dherp = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Dhiv = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Dhpv = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Doenc = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Dsifil = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Dtrico = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ExamAnua = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Gdescobrindo = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Gestacao = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Gevolucao = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Gmudancas = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Gparto = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Gprimeiros = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Gpuerperio = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Gsinais = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Gsono = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Information = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Main = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int MetConcep = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int ObjMil = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Prevencao = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Principal = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Promocao = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int ProtecaoGestacao = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SUS = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int Trimestre1 = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int Trimestre2 = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int Trimestre3 = 2130903072;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
